### ISSUE TITLE
Make gateway properties selectable

### ISSUE THREAD

**Issue by pattyland** [dresden-elektronik/phoscon-app-beta#151]
If I have a bug of Phoscon/deCONZ is really good if you write the version you just installed. The easy way would be to simply copy it from Phoscon. Unfortunately this selection is prohibited via CSS. I think it would be helpful to change this!

```css
#settingsGwContent {
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}
```
