### ISSUE TITLE
"Single" toggle doesn't stick in groups

### ISSUE THREAD

**Issue by deviantintegral** [dresden-elektronik/phoscon-app-beta#340]
When I flip the toggle from "All" to "Single, after a few seconds it goes back to "All". This is with a ConBee II 26660700 / Phoscon 2.09.03 / 2020-12-23. I ended up having to create a dedicated "Espresso Outlet" group for the outlet so it wasn't tied to the state of the light.

<img width="422" alt="Screen Shot 2021-02-19 at 6 35 46 AM" src="https://user-images.githubusercontent.com/255023/108605059-c0588680-737f-11eb-88ee-427bb4023898.png">

**Comment by SEK-DE** [comment]
We couldn´t reproduce the bug. Can you tell what you want to do exactly?

**Comment by deviantintegral** [comment]
Thanks for taking a look. I took a look again and I discovered this was due to the `flux` configuration I had in Home Assistant. I had the following configured, where `light.kitchen` is the group:

```
# Flux configurations
switch:
  # Flux for full RGB lights
  - platform: flux
    lights:
      - light.kitchen
    name: Kitchen flux
    start_time: "6:00"
    stop_time: "23:00"
    start_colortemp: 7000
    sunset_colortemp: 5000
    stop_colortemp: 2000
    mode: xy
```

I had thought that only lights in the group would be affected. Of course, the switch is seen as a "light", so any time Flux sent an update (pretty often) the command would be forwarded to the outlet. I can change that to send directly to the device, or have a separate group as I mentioned above.

Sorry for the goose chase! My only suggestion - it would be very nice to have a logging / debugging mode that would show rest API requests from deconz in Phoscon. Or, at least some instructions at https://www.phoscon.de/en/support/ on how to enable logging.
